### ISSUE TITLE
Use enum for status, rather than multiple booleans

### ISSUE THREAD

**Issue by andreyrd** [vitaliyrd/inventory-backend#3]

**Comment by andreyrd** [comment]
On the other hand, this may not be as flexible, since we might want to have multiple status flags on at the same time. I'm going to close this for now until we have a good reason to do it.

**Comment by vitaliyrd** [comment]
Yeah, we might use enums for things later like broken, under repair, or ready. But for things like checked in/out it will be better to use booleans.

**Comment by andreyrd** [comment]
My view is that it's better to even have those as booleans. Easier to manage database updates to be working on separate fields instead of cramming everything into one field and having to constantly change the data type of that one field.
